### ISSUE TITLE
won't build  - crashes on of0.9.8 OS X 10.11.6 64

### ISSUE THREAD

**Issue by steeley** [elliotwoods/ofxSquash#13]
Spent hours trying to get this to work...

64 bit builds crash when trying to load the dylib. even just including #include "ofxSquash.h"
causes a crash

simple sample app works from within addons only.

 32 bit is probably ok. ?? Nope...
tried 32 bit but just get these errors:
  "_squash_foreach_codec", referenced from:

  "_squash_set_default_search_path", referenced from:

  "_squash_codec_get_name", referenced from:

  "_squash_codec_init", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by elliotwoods** [comment]
if you simply move the executable from one place to another do you still experience the crash?
perhaps the project has some hard-wired paths for parts it includes in the executable

also it's useful to try removing all the squash plugins, and then introduce them a bit at a time to identify if a particular plugin is causing the issue

**Comment by steeley** [comment]
moving the executable on  its own will crash because it has no plugins...
move the bin folder and the simpleExample binary works.
This is the only thing that works.

As far as I can see this addon will never work properly.
Even making a blank project and no code except including the header will crash.

**Comment by elliotwoods** [comment]
Sorry for the problems you see
This addon was mostly developed, tested and deployed on Windows.
We tested and got it running on OSX, but perhaps didn't quite get everything ironed out as you have experienced.

so most likely is a cross-platform issue with paths (common issue for cross-platform compatibility)

as a quick fix, i would suggest hard-coding a path into 
https://github.com/elliotwoods/ofxSquash/blob/master/src/ofxSquash/Initializer.cpp#L20 
to see if that works for you

if it does work, then perhaps you can find a simple way to make it work for you in general on osx (or even a general fix and a PR would be amazing).

Again, sorry if this issue is a show-stopper for you right now
i hope that pointing you to where the issue is likely to stem from will help you get where you need to be. The addon is generally quite well written, so i'm sorry to hear that it isn't working for your case right now.

**Comment by steeley** [comment]
Thanks - will have a look when i get more time. Its potentially a good addon so be nice if it can work cross platform.
