### ISSUE TITLE
Lossless compression

### ISSUE THREAD

**Issue by wasawi** [elliotwoods/ofxSquash#5]
Ok just realized all compressors are lossless..
Is there any plans to include image compression on top of it?

**Comment by elliotwoods** [comment]
All compression algorithms are lossless so far
Do you mean lossy compression?

**Comment by elliotwoods** [comment]
from skype you mentioned you clarified you meant lossy

I've been considering how this might work
Firstly, the underlying library Squash would need to implement this
https://github.com/quixdb/squash

Next, this type of compression is always domain specific, and requires other known parameters about the data (e.g. width/height of image, channel count, image data type).
This could be passed into the compressor as parameters, so it is feasible

The main question is whether the Squash team would be happy with considering lossy data types. I think it's a discussion worth having, but it's also likely something they might not be interested in.

I'm going to close here because there's it wouldn't be right to implement this in ofxSquash itself, since it would need to be implemented in the underlying library.

**Comment by wasawi** [comment]
Thank you for clarifying! 
I understand its better that one takes care of it out of the addon.
